apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - name: ssh-port
      protocol: TCP
      port: 22
      targetPort: 22
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-port
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 172.17.0.4
