apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
    - port: 22
      name: ssh
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 172.17.0.2
