apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: my_nginx
        name: nginx
        imagePullPolicy: Never
        ports:
          - name: ssh-port
            containerPort: 22
          - name: http-port
            containerPort: 80
          - name: https-port
            containerPort: 443
