apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
    - name: wp-port
      protocol: TCP
      port: 5050
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 172.17.0.2
