apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: my_wordpress
        imagePullPolicy: Never
        ports:
        - name: wp-port
          containerPort: 5050
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "service telegraf status && service mariadb status && service nginx status && service php-fpm7 status"
          initialDelaySeconds: 5
          periodSeconds: 5
