apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: ClusterIP
  ports:
    - name: idb-port
      protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
