apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-service
spec:
  selector:
    matchLables:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21100
        - containerPort: 21101
        - containerPort: 21102
        - containerPort: 21103
        - containerPort: 21104
        - containerPort: 21105
        - containerPort: 21106
        - containerPort: 21107
        - containerPort: 21108
        - containerPort: 21109
        - containerPort: 21110
