apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - name: ftp
          containerPort: 20
        - name: ftps
          containerPort: 21
        - name: pasv0
          containerPort: 21009
        - name: pasv1
          containerPort: 21010
        - name: pasv2
          containerPort: 21011
