apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  ports:
    - name: graf-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 172.17.0.5
