# Generated by Django 3.2.4 on 2021-06-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Your tip', max_length=2048)),
                ('author', models.CharField(help_text='Your username', max_length=64)),
                ('date', models.DateField(help_text="Today's date", null=True)),
            ],
        ),
    ]
