# Generated by Django 3.2.4 on 2021-06-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=models.TextField(help_text='Your tip'),
        ),
    ]
