# Generated by Django 3.2.4 on 2021-06-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_alter_tip_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='author',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
