# Generated by Django 3.2.4 on 2021-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_auto_20210623_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='btn',
            field=models.CharField(default=False, max_length=1),
        ),
    ]
