# Generated by Django 3.2.4 on 2021-06-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_tip_btn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='btn',
            new_name='delete',
        ),
        migrations.AddField(
            model_name='tip',
            name='downvote',
            field=models.CharField(default=False, max_length=1),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvote',
            field=models.CharField(default=False, max_length=1),
        ),
    ]
