# Generated by Django 3.2.4 on 2021-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flash',
            name='delete',
            field=models.CharField(default=False, max_length=1),
        ),
    ]
