apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  ports:
    - port: 5000
    - targetPort: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 172.17.0.3
